### ISSUE TITLE
Support fallback default for `.require()`

### ISSUE THREAD

**Issue by bradleyayers** [bloomtime/require-env#6]
Would you be interested in allowing `.require()` to accept an optional second argument that is used as a fallback value (instead of raising an exception)?

**Comment by sethfitz** [comment]
Not really; the `var thing = process.env.THING || "fallback";` pattern should suffice for that (and such environment vars don't feel strictly required since a fallback is available). I'm happy to be convinced otherwise though.

**Comment by bradleyayers** [comment]
Fair enough, it's really an issue of consistency and aesthetics, so I don't think I'd be able to make a compelling argument. Thanks for the quick response regardless.
